### PR TITLE
Fobnail sdk v0.2.0 compatibility

### PR DESCRIPTION
**Pull request by macpijan**
This should be tested with fonbail-sdk v0.2.0 from: https://github.com/fobnail/fobnail-sdk/pull/3

The `run-fobnail-sdk.sh` script should be in PATH as explained in the updated README of the `fobnail-sdk`.

The reasoning is to keep the docker wrapper script inside one repo (fobnail-sdk) rather than scattering it here and there in some parts.

### CODE REVIEW

**Comment by macpijan** [comment]
@arturkow2000 @krystian-hebel Have you tried this?

The fobnail-sdk v0.2.0 was already merged and the tag v0.2.0 was published: https://github.com/fobnail/fobnail-sdk/pull/3

**Comment by krystian-hebel** [comment]
I've tried and it worked on main branch at that time, but stopped working on any other. This may have been due to some flags passed to docker being skipped during rebasing, though.

**Comment by macpijan** [comment]
@krystian-hebel I'm merging it then. If it does not work, let's complain and fix.

**Comment by macpijan** [comment]
@krystian-hebel @arturkow2000 I've added CI to track the build status. After merging, building for nRF actually fails: https://github.com/fobnail/fobnail/runs/5455230335?check_suite_focus=true

Not sure if this is related to the new SDK in any way, though.

**Pull request merged**
